config/routes.rb
Rails.application.routes.draw do
  
 
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :food_images
  resources :user_images
  root :controller => 'static', :action => :home
  #resources :orders
  resources :users do
    resources :user_images
    member do
    get :follow
    get :unfollow
  end
  end
  
  # for mapping the common 8 methods to the respective uris
  resources :food_items do
    resources :food_images
    resources :food_reviews
  end
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  match '/login', to:'sessions#login', via: :post
  match '/signup', to:'sessions#signup', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/login_form', to: 'sessions#login_form', via: :get
  match '/signup_form', to: 'sessions#signup_form', via: :get
  match '/signup_confirm', to: 'sessions#signup_confirm', via: :get
  match '/update_form', to: 'users#update_form', via: :get
  
  match '/orders/order', to: 'orders#order', via: :post, as: :place_order
  match '/orders/:id', to: 'orders#show', via: :get, as: :order
  match '/orders/status/:id', to: 'orders#change_status', via: :post, as: :change_status
  match '/food_items/:id/availability_update', to: 'food_items#update_availability_only', via: :put, as: :food_items_availability_update
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    ZIP_REGEX = /\A[0-9]{5}\z/
    EMAIL_REGEX = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates :first_name, :presence => true
    validates :last_name, :presence => true
    validates :email, :presence => true, :format => {:with => EMAIL_REGEX}, :uniqueness => {case_sensitive:false}
    validates :address_one, :presence => true
    validates :city, :presence => true
    validates :state, :presence => true
    validates :zip, :presence => true, :format => {:with => ZIP_REGEX}
    
    validate :address_is_valid
    
    def address_is_valid
        @coordinates = Geocoder.coordinates(full_address)
        if not @coordinates
            errors.add(:address, "Sorry, this address to not seem to be valid: please double check it")
        end
    end
    
    #save coordinates for a user based on their address
    geocoded_by :full_address
    after_validation :geocode
    
    reverse_geocoded_by :latitude, :longitude

    # concatenation of first and last name. If either is nil, just returns
    # the other alone
    def full_name
        if (last_name==nil)
            return first_name
        end
        if (first_name==nil)
            return last_name
        end
        return first_name + " " + last_name
    end
    
    # Returns the users full address as a string
    def full_address
        addr = self.address_one
        if (self.apt_num)
            addr+= (" "+self.apt_num)
        end
        if (self.address_two) 
            addr+="\n"
            addr+=self.address_two
        end
        addr+="\n"
        addr+=self.city+", "+self.state+", "+self.zip
    end
    
    # Generates and also saves a password reset token for this user
    def generate_password_reset_token!
        update_attribute(:password_reset_token, SecureRandom.urlsafe_base64)
    end
    
    # Determines whether this user has an associated profile picture
    def has_image
        return self.user_images.size>0
    end
    
    def following?(ouser)
        self.following.include?(ouser)
    end
 
    
    has_many :food_items, dependent: :destroy
    has_many :orders_as_customer, :class_name => 'Order', :foreign_key => 'customer_id', dependent: :destroy
    has_many :orders_as_seller, :class_name => 'Order', :foreign_key => 'seller_id', dependent: :destroy
    has_many :food_reviews, dependent: :destroy
    has_many :user_images, dependent: :destroy
    has_many :follows, :class_name => 'Follow', :foreign_key => "user_id", dependent: :destroy
    has_many :followers,:through => :follows, source: :user
    has_many :following,:through => :follows, source: :cook
    
end

app/controllers/users_controller.rb
require 'states'
class UsersController < ApplicationController
    

    before_filter :set_current_user
    
    before_filter :assert_login, :only => [:destroy, :update, :update_form]


   def user_params
      params.require(:user).permit(:first_name, :availability, :last_name,:address_one, 
       :address_two, :apt_num, :city, :state, :zip)
   end
    
   def destroy
        @user = User.find_by_id(params[:id]) 
        @user.destroy
        flash[:notice] = "User Account Deleted."
        redirect_to root_path
   end
    
   def show
        id = params[:id] 
        @user = User.find(id)
        
   end

   def update
     @user = get_current_user
     @states = StatesHelper.states
     if @user.update_attributes(user_params)
          flash[:notice] = "Updated successfully"
          redirect_to user_path(@current_user)
      else
          @errors = @user.errors.full_messages
          render 'update_form'
     end
   end
    
   def update_form
      @user = get_current_user
      @states = StatesHelper.states
   end
   
   def follow
       id = params[:id]
       @user = User.find(id)
       if @user == @current_user
           flash[:notice] = "Cannot follow yourself"
           redirect_to food_item_path(params[:food_id])
       else
           @follow = Follow.create(:cook_id=> @user.id, :user_id=> @current_user.id)
           @follow.save
           flash[:notice] = "You followed #{@user.full_name}"
           redirect_to food_item_path(params[:food_id])
       end
       return
   end
   
   def unfollow
       id = params[:id]
       @user = User.find(id)
       follow = Follow.find_by(:cook => @user, :user => @current_user)
       if not follow.nil?
           follow.destroy
       end
       flash[:notice] = "You unfollowed #{@user.full_name}"
       if not params[:food_id].nil?
        redirect_to food_item_path(params[:food_id])
       else
        redirect_to root_path
       end
       return
   end
    
end

app/views/users/show.html.haml
#tabs
  %ul
    %li
      <a href="#tabs-1">Profile</a>
    %li
      <a href="#tabs-2">Foods</a>
    - if @current_user!=nil and @current_user.id==@user.id
      %li
        <a href="#tabs-3">Transactions</a>
      %li
        <a href="#tabs-4">Following</a>
    
  #tabs-1
    #user_images_div
      #slides_user
        - if @user.has_image
          - @user.user_images.each do |p|
            %div.slide_wrapper
              %span.image_wrapper
                = image_tag image_path(p.relative_path)
                = link_to "Delete Image", user_user_image_path(@user, p), :method => :delete, :class => "image_delete", :onclick => "return confirm('Are you sure you want to delete this image?')"
  
        - else
          %span.image_wrapper
            = image_tag image_path("no_image.jpg")

    #user_detail_div          
      %h2 Personal Details
      %p= "First Name: " + @user.first_name
      %p= "Last Name: " + @user.last_name
      %p= "Email Name: " + @user.email
      %h2 Address
      %pre= @user.full_address
      - if @current_user!=nil and @current_user.id==@user.id
        =button_to "Edit Profile", update_form_path, :method => :get
        - if @user.availability
          = button_to "Make Unavailable", user_path(@user, :user => {:availability => false}), :method => :put, :id => 'toggle_avail'
        - else
          = button_to "Make Available", user_path(@user,:user => {:availability => true}), :method => :put, :id => 'toggle_avail'
        = button_to "Add Your Photo", new_user_user_image_path(@user), :method=>:get

  #tabs-2
    - @user.food_items.each do |food|
      %div.food_detail_div
        %div.food_image_thumb
          - if food.has_image
            %span.image_wrapper
              = image_tag image_path(food.food_images.first.relative_path)
          - else
            %span.image_wrapper
              = image_tag image_path("no_image.jpg")
        %p.food_detail_name= link_to "#{food.name}", food_item_path(food)
        %p.food_detail_description= food.short_description
    = link_to 'Add Food item', new_food_item_path
  - if @current_user!=nil and @current_user.id==@user.id
    #tabs-3
      %table#order
        %thead
          %tr
            %th Order Number
            %th Food Item
            %th Description
            %th Bought/Sold
            %th More Info
            %th Review
        %tbody
          - if not @user.orders_as_customer.nil?
            - @user.orders_as_customer.each do |order|
              %tr
                %td= order.id
                %td= order.food_item_portion.food_item.name
                %td= order.food_item_portion.food_item.description
                %td  Bought
                %td= link_to "More info", order_path(order.id)
                %td= link_to "Write review", new_food_item_food_review_path(order.food_item_portion.food_item.id)
          - if not @user.orders_as_seller.nil?
            - @user.orders_as_seller.each do |order|
              %tr
                %td= order.id
                %td= order.food_item_portion.food_item.name
                %td= order.food_item_portion.food_item.description
                %td  Sold
                %td= link_to "More info", order_path(order.id)
                %td= link_to "read review", food_item_food_reviews_path(order.food_item_portion.food_item), :method => :get
    #tabs-4
      %table#follow
        %thead
          %tr
            %th Cook Name
            %th Action
        %tbody
          -if not @user.following.nil?
            - @user.following.each do |follow|
              %tr
                %td= follow.full_name
                %td= link_to "Unfollow", unfollow_user_path(follow)
          
        

app/views/users/update_form.html.haml
= form_tag @user, :method => :put  do 
    
    = label :user,:first_name, "First Name"
    = text_field :user, :first_name
    
    = label :user,:last_name, 'Last Name:'
    = text_field :user, :last_name
    
    %h2 Address
    = label :user, 'Line 1:'
    = text_field :user, :address_one
    = label :user, 'Line 2:'
    = text_field :user, :address_two
    = label :user, 'Apt #:'
    = text_field :user, :apt_num
    = label :user, 'City:'
    = text_field :user, :city
    = label :user,'State:'
    = select :user, 'state', options_for_select(@states, selected: @current_user.state)
    = label :user,'Zip:'
    = text_field :user, :zip, :maxlength => 5
    = submit_tag 'Update' 
    
= button_to 'Cancel', user_path(@current_user), :method=>:get

= link_to "Delete My Account", user_path(@current_user), :method=>:delete, data: {confirm: "Are you sure to delete your account?"}