config/routes.rb
Rails.application.routes.draw do
  
 
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :food_images
  resources :user_images
  root :controller => 'static', :action => :home
  #resources :orders
  resources :users do
    resources :user_images
    member do
    get :follow
    get :unfollow
  end
  end
  
  # for mapping the common 8 methods to the respective uris
  resources :food_items do
    resources :food_images
    resources :food_reviews
  end
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  match '/login', to:'sessions#login', via: :post
  match '/signup', to:'sessions#signup', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/login_form', to: 'sessions#login_form', via: :get
  match '/signup_form', to: 'sessions#signup_form', via: :get
  match '/signup_confirm', to: 'sessions#signup_confirm', via: :get
  match '/update_form', to: 'users#update_form', via: :get
  
  match '/orders/order', to: 'orders#order', via: :post, as: :place_order
  match '/orders/:id', to: 'orders#show', via: :get, as: :order
  match '/orders/status/:id', to: 'orders#change_status', via: :post, as: :change_status
  match '/food_items/:id/availability_update', to: 'food_items#update_availability_only', via: :put, as: :food_items_availability_update
end

app/controllers/food_reviews_controller.rb
class FoodReviewsController < ApplicationController
  
  before_action :set_food_review, only: [:show, :edit, :update, :destroy]
  before_action :set_food_item

  # GET /food_reviews
  # GET /food_reviews.json
  def index
    @food_reviews=FoodReview.where(food_item_id: @food_item.id)
  end

  # GET /food_reviews/new
  def new
    @food_review = FoodReview.new
  end

  # GET /food_reviews/1/edit
  def edit
  end

  # POST /food_reviews
  # POST /food_reviews.json
  def create
    @food_review = FoodReview.new(food_review_params)
    @user=get_current_user
    @food_review.user_id = @user.id
    @food_review.food_item_id = @food_item.id

    respond_to do |format|
      if @food_review.save
        format.html { redirect_to @food_item, notice: 'Food review was successfully created.' }
        format.json { render :show, status: :created, location: @food_review }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_reviews/1
  # PATCH/PUT /food_reviews/1.json
  def update
    respond_to do |format|
      if @food_review.update(food_review_params)
        format.html { redirect_to food_item_food_reviews_path(@food_item), notice: 'Food review was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_review }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_reviews/1
  # DELETE /food_reviews/1.json
  def destroy
    @food_review.destroy
    respond_to do |format|
      format.html { redirect_to food_item_food_reviews_path(@food_item), notice: 'Food review was successfully destroyed.' }
      format.json { head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_review
      @food_review = FoodReview.find(params[:id])
    end
    
    def set_food_item
      @food_item = FoodItem.find(params[:food_item_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_review_params
      params.require(:food_review).permit(:rating, :comment)
    end
end

app/helpers/food_reviews_helper.rb
module FoodReviewsHelper
end

app/views/food_reviews/_form.html.haml
= form_for ([@food_item, @food_review]) do |f|
  - if @food_review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food_review.errors.count, "error")} prohibited this food_review from being saved:"
      %ul
        - @food_review.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :rating
    = select :food_review, 'rating', options_for_select([1,2,3,4,5])
  .form-group
    = f.label :comment, "Comments"
    = f.text_area :comment
  .form-group
    = f.submit 'Save'

app/views/food_reviews/edit.html.haml
%h1 Editing Food Reviews

= render 'form'

app/views/food_reviews/index.html.haml
%h1 Listing Food Reviews

%table
  %thead
    %tr
      %th Rating
      %th Author
      %th Comments
      %th
      %th

  %tbody
    - @food_reviews.each do |food_review|
      %tr
        %td= food_review.rating
        %td
          %a{:href => user_path(food_review.user)}
            %span= food_review.user.full_name
        %td= food_review.comment
        - if @current_user!=nil and @current_user.id=food_review.user_id
          %td= link_to 'Edit', edit_food_item_food_review_path(food_review.food_item, food_review)
          %td= link_to 'Delete', [food_review.food_item, food_review] , :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/food_reviews/new.html.haml
%h1= "New Food Review for " + @food_item.name

= render 'form'