config/routes.rb
Rails.application.routes.draw do
  
 
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :food_images
  resources :user_images
  root :controller => 'static', :action => :home
  #resources :orders
  resources :users do
    resources :user_images
    member do
    get :follow
    get :unfollow
  end
  end
  
  # for mapping the common 8 methods to the respective uris
  resources :food_items do
    resources :food_images
    resources :food_reviews
  end
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  match '/login', to:'sessions#login', via: :post
  match '/signup', to:'sessions#signup', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/login_form', to: 'sessions#login_form', via: :get
  match '/signup_form', to: 'sessions#signup_form', via: :get
  match '/signup_confirm', to: 'sessions#signup_confirm', via: :get
  match '/update_form', to: 'users#update_form', via: :get
  
  match '/orders/order', to: 'orders#order', via: :post, as: :place_order
  match '/orders/:id', to: 'orders#show', via: :get, as: :order
  match '/orders/status/:id', to: 'orders#change_status', via: :post, as: :change_status
  match '/food_items/:id/availability_update', to: 'food_items#update_availability_only', via: :put, as: :food_items_availability_update
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  
    belongs_to :user
    has_many :food_item_portions, dependent: :destroy
    has_many :food_images, dependent: :destroy
    has_many :food_reviews, dependent: :destroy
    
    accepts_nested_attributes_for :food_images
    
    SHORT_SIZE_LIMIT=100

    validates :name, :presence => true
    validates :category, :presence => true
    
    # Returns the description of this item truncated to 100 characters.
    # This is used for display on the search page, for example, where space
    # is limited.
    def short_description
        if self.description.size<SHORT_SIZE_LIMIT
            return self.description
        end
        return self.description[0,SHORT_SIZE_LIMIT]+"..."
    end
    
    # Returns a list of FoodItem records given a hash of values to search by
    # Any hash entries that are not present are simply not used as filters
    # The exception is location, which is required
    # Only available food items are shown
    def self.search(hash, coordinates)
        hash.default =""
        items = FoodItem.where(:availability => true).joins("JOIN users ON (food_items.user_id=users.id AND (users.availability OR users.availability='t'))")
        .joins("LEFT OUTER JOIN food_images ON food_images.food_item_id=food_items.id"
        ).where("name LIKE :name AND category LIKE :category AND (food_images.avatar IS NOT NULL OR :images!='1')",
        name: "%#{hash[:name]}%",
        category: "%#{hash[:category]}%",
        images: hash[:only_images].to_s).distinct
        finalItems = []
        items.each do |item|
            item.set_rating
            if ((!hash.has_key?(:radius) or (item.user.distance_from(coordinates) <= hash[:radius].to_i)) and (!hash.has_key?(:rating) or (item.rating >= hash[:rating].to_i)))
                finalItems << item
            end
        end
        return FoodItem.sortList finalItems,hash[:do_sort]
    end
    
    # Checks whether this item has any associated images.
    def has_image
        return self.food_images.size>0
    end
    
    def has_rating
        return (self.food_reviews!=nil and self.food_reviews.length > 0)
    end
    
    def rating
        @food_rating
    end
    
    # computes average rating out of 5. If the food has no reviews, 0.0 is the socre
    def set_rating
        food_reviews = self.food_reviews
        if self.has_rating
            totrating = 0
            food_reviews.each do |food_review|
                totrating = totrating + food_review.rating
            end
            avg_rating = totrating.to_f/food_reviews.length
            @food_rating = avg_rating.round(2)
            return
        end
        @food_rating = 0.0
    end
    
    def self.sortList food_items, do_sort
        if not do_sort.nil? and do_sort.to_s == "1" and not food_items.nil? and food_items.length > 0
            for i in 0..(food_items.length-2)
                for j in 1..(food_items.length-1)
                    if food_items[i].rating < food_items[j].rating
                        food_items[i], food_items[j] = food_items[j], food_items[i]
                    end
                end
            end 
        end
        return food_items
    end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController

  before_filter :assert_login, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :assert_matching_user, :only =>[:edit, :update, :destroy]
  
  def assert_matching_user
    item = FoodItem.find_by_id(params[:id])
    if item==nil 
      flash[:notice] = "Sorry, that food could not be found."
      redirect_to root_path
      return
    end
    if item.user.id!=@current_user.id
      flash[:notice] = "You may only modify your own menu"
      redirect_to root_path
    end
  end
  
  def food_item_params
    params.require(:food_items).permit(:name, :category, :description, :availability,
    :only_images, food_images_attributes:[:id,:post_id,:avatar]).tap do |whitelisted|
      whitelisted[:portion] = params[:food_items][:portion]
      whitelisted[:price] = params[:food_items][:price]
    end
  end

  def show
    @food_item = FoodItem.find(params[:id])
    @food_image = @food_item.food_images.all
  end
  
  def index
  end

  def new
    
    if @food_item_defaults==nil
      @food_item_defaults = {}
    end
    
    if @portion_defaults==nil
      @portion_defaults = {}
    end
    
    if @price_defaults==nil
      @price_defaults = {}
    end
    
    if @avatar_defaults == nil
      @avatar_defaults ={}
    end
    
  end
  
  def create
    user = User.find(session[:user_id])
    
    @food_item = user.food_items.build(:name => food_item_params[:name], :category => food_item_params[:category], 
                  :description => food_item_params[:description])
    
    @food_item.transaction do
      
      if @food_item.save
        
        food_item_params[:portion].keys.each do |portionKey|
          @food_item_portion = @food_item.food_item_portions.build(:portion => food_item_params[:portion][portionKey], 
                                :price => food_item_params[:price][portionKey])
          if not @food_item_portion.save
            @errors = @food_item_portion.errors.full_messages
            @food_item_defaults = food_item_params
            @portion_defaults = food_item_params[:portion]
            @price_defaults = food_item_params[:price]
            render 'new'
            raise ActiveRecord::Rollback
          end
        end
      else
        @errors = @food_item.errors.full_messages
        @food_item_defaults = food_item_params
        @portion_defaults = food_item_params[:portion]
        @price_defaults = food_item_params[:price]
        render 'new'
        raise ActiveRecord::Rollback
      end
      flash[:notice] = "#{@food_item.name} was successfully created."
      redirect_to user_path(get_current_user)
      return
    end
  end

  def edit
    @food_items = FoodItem.find(params[:id])
    
    if @food_item_defaults==nil
      @food_item_defaults = {}
    end
    
    if @portion_defaults==nil
      @portion_defaults = {}
    end
    
    if @price_defaults==nil
      @price_defaults = {}
    end
    
  end
  
  # simpler path that updates only whether a food item is available or not.
  def update_availability_only
    @food_item = FoodItem.find(params[:id])
     if @food_item.update_attributes(:availability => food_item_params[:availability])
          flash[:notice] = "Updated successfully"
      else
          flash[:notice] = "Unable to update availability"
     end
      redirect_to food_item_path(@food_item)

  end

  def update
    @food_item = FoodItem.find(params[:id])
    @food_item.name = food_item_params[:name] 
    @food_item.category = food_item_params[:category]
    @food_item.description = food_item_params[:description]
    
    @food_items = @food_item
    @food_item.transaction do
      
      if @food_item.save     
        
        @food_item.food_item_portions.destroy_all
        food_item_params[:portion].keys.each do |portionKey|
          @food_item_portion = @food_item.food_item_portions.build(:portion => food_item_params[:portion][portionKey], 
                                :price => food_item_params[:price][portionKey])
          if not @food_item_portion.save
            @errors = @food_item_portion.errors.full_messages
            @food_item_defaults = food_item_params
            @portion_defaults = food_item_params[:portion]
            @price_defaults = food_item_params[:price]
            render 'edit', :id => @food_item.id 
            raise ActiveRecord::Rollback
          end
        end
      else
        @errors = @food_item.errors.full_messages
        @food_item_defaults = food_item_params
        @portion_defaults = food_item_params[:portion]
        @price_defaults = food_item_params[:price]
        render 'edit', :id => @food_item.id
        raise ActiveRecord::Rollback
      end
      flash[:notice] = "#{@food_item.name} was successfully updated."
      redirect_to food_item_path(@food_item)
      return
    end
  end

  # Deletes both a food item and all associated protions
  def destroy
    @food_item = FoodItem.find(params[:id])
    food_item_name = @food_item.name
    @food_item.transaction do
      if not @food_item.food_item_portions.nil?
        @food_item.food_item_portions.destroy_all
      end
      @food_item.destroy!
      flash[:notice] = "#{food_item_name} was successfully deleted."
      redirect_to user_path(get_current_user)
    end
  end
  
  # This is the action associated with searching for food items. It requires
  # that some location be set, as we want to restrict users to searching in 
  # some geographical area. This is not necessary with a small dataset like ours,
  # but it would be critical in a real app that has many users.
  def index
    @defaults = {}
    if (params[:food_items]!=nil)
      @defaults = params[:food_items]
    end
    @coordinates = Geocoder.coordinates(@defaults["location"])
    if (not @coordinates)
      @errors = ["Location could not be found: please enter a valid address or city"]
      @foods = []
      return
    end
    @foods = FoodItem.search(@defaults, @coordinates)
  end
end

app/views/food_items/add_image.html.haml
= form_for(@food_item, :html => { :multipart => true }) do |f|
  .field
    = f.label :title
    %br
      = f.text_field :title
  = f.fields_for :food_images do |p|
    .field
      = p.label :avatar
      %br
        = p.file_field :avatar, :multiple => true, name: "food_images[avatar][]"
  .actions
    = f.submit

app/views/food_items/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing FoodItem

= form_tag food_item_path(@food_items), :method => :put do
  %ul
    %li
      = label :food_items, :name, 'Name'
      - if @food_item_defaults["name"].nil?
        = text_field :food_items, 'name'
      - else
        = text_field :food_items, 'name', :value => @food_item_defaults["name"]
    %li
      = label :food_items, :category, 'Category'
      - if @food_item_defaults["category"].nil?
        = text_field :food_items, 'category'
      - else
        = text_field :food_items, 'category', :value => @food_item_defaults["category"]
    %li
      = label :food_items, :descritpion, 'Description'
      - if @food_item_defaults["description"].nil?
        = text_field :food_items, 'description'
      - else
        = text_field :food_items, 'description', :value => @food_item_defaults["description"]
    %li
      #Portions
        -if @portion_defaults.nil? or @portion_defaults.empty?
          - counter = 0      
          - @food_items.food_item_portions.each do |portion|
            %div{:id => "Portion#{(counter+1)}"}
              = label :food_items, :portion[counter], "Portion # #{(counter+1)}: "
              = text_field :food_items, "portion[#{counter}]", :value => portion.portion
            
              = label :food_items, :price[counter], 'Price : '
              = text_field :food_items, "price[#{counter}]", :value => portion.price
            - counter = counter + 1
        -else
          - @portion_defaults.keys.each do |portionKey|
            %div{:id => "Portion#{(portionKey.to_i+1)}"}
              = label :food_items, :portion[portionKey], "Portion # #{(portionKey.to_i+1)}: "
              = text_field :food_items, "portion[#{portionKey.to_i}]", :value => @portion_defaults["#{portionKey}"]
              
              = label :food_items, :price[portionKey], 'Price : '
              = text_field :food_items, "price[#{portionKey.to_i}]", :value => @price_defaults["#{portionKey}"]
        
    %li      
      %input#addFIPortion{:type => "button", :value => "Add Portion"}
      %input#removeFIPortion{:type => "button", :value => "Remove Portion"}
  
  = submit_tag 'Update Food Item'

app/views/food_items/index.html.haml
#search_column
    = form_tag food_items_path, :method => :get do
        %ul
            %li
                = label :food_items, :name, 'Name'
                = text_field :food_items, 'name', :value => @defaults["name"], :class => "search_food_filter_tab search_text_box"
            %li
                = label :food_items, :category, 'Category'
                = text_field :food_items, 'category', :value => @defaults["category"], :class => "search_food_filter_tab search_text_box"
            %li
                = label :food_items, :location, 'Location'
                = text_field :food_items, 'location', :value => @defaults["location"], :class => "search_food_filter_tab search_text_box"
            %li
                = label :food_items, :radius, 'Radius:'
                = select :food_items, 'radius', options_for_select([5,10,25,50,100], @defaults["radius"])
            %li
                = label :food_items, :rating, 'Rating:'
                = select :food_items, 'rating', options_for_select([["", 0],["1 or above", 1],["2 or above", 2],["3 or above", 3],["4 or above", 4],["5", 5]], @defaults["rating"])
            %li
                %h3 Filters
            %li
                = label :food_items, :only_images, 'Images Only', :class=>'inline';
                = check_box :food_items, 'only_images', :checked => (not @defaults["only_images"].nil? and @defaults["only_images"].to_s == "1")
            %li
                = label :food_items, :do_sort, 'Sort By Rating', :class=>'inline';
                = check_box :food_items, 'do_sort', :checked_value => "1", :unchecked_value => "0", :checked => (not @defaults["do_sort"].nil? and @defaults["do_sort"].to_s == "1")
        = submit_tag 'Search'
#results_column
    - if @foods.length>0
        - @foods.each do |food|
            %div.food_detail_div
                %div.food_image_thumb
                    - if food.has_image
                        %span.image_wrapper
                            = image_tag image_path(food.food_images.first.relative_path)
                    - else
                        %span.image_wrapper
                            = image_tag image_path("no_image.jpg")
                %p.food_detail_name= link_to "#{food.name}", food_item_path(food)
                %p.food_detail_description= food.short_description
                -if food.has_rating
                    %p.food_detail_rating= "Rating: "+food.rating.to_s
                -else
                    %p.food_detail_rating= "Rating: None"
                %p.food_detail_distance= "Distance: "+food.user.distance_from(@coordinates).to_i.to_s
    - else
        %div.food_not_found_div
            %p Sorry, we couldn't find any matching foods. Please try editing your search query

app/views/food_items/new.html.haml
%h1 Add a Food Item

= form_tag food_items_path do
  %ul
    %li
      = label :food_items, :name, 'Name : '
      = text_field :food_items, 'name', :value => @food_item_defaults["name"]
    
    %li
      = label :food_items, :category, 'Category : '
      = text_field :food_items, 'category', :value => @food_item_defaults["category"]
    
    %li  
      = label :food_items, :description, 'Description : '
      = text_field :food_items, 'description', :value => @food_item_defaults["description"]
    
    %li
      #Portions
        -if @portion_defaults.nil? or @portion_defaults.empty?
          %div#Portion1
            = label :food_items, :portion[0], 'Portion # 1 : '
            = text_field :food_items, 'portion[0]'
            
            = label :food_items, :price[0], 'Price : '
            = text_field :food_items, 'price[0]'
        -else
          - @portion_defaults.keys.each do |portionKey|
            %div{:id => "Portion#{(portionKey.to_i+1)}"}
              = label :food_items, :portion[portionKey], "Portion # #{(portionKey.to_i+1)}: "
              = text_field :food_items, "portion[#{portionKey.to_i}]", :value => @portion_defaults["#{portionKey}"]
            
              = label :food_items, :price[portionKey], 'Price : '
              = text_field :food_items, "price[#{portionKey.to_i}]", :value => @price_defaults["#{portionKey}"]
    
    %li
      %input#addFIPortion{:type => "button", :value => "Add Portion"}
      %input#removeFIPortion{:type => "button", :value => "Remove Portion"}
    
  = submit_tag 'Save'

app/views/food_items/show.html.haml
#food_image_div 
  #slides
    - if @food_item.has_image
      - @food_item.food_images.each do |p|
        %div.slide_wrapper
          %span.image_wrapper
            = image_tag image_path(p.relative_path)
          - if @current_user!=nil and @current_user.id == @food_item.user_id
            = link_to "Delete Image", food_image_path(p), :method => :delete, :class => "image_delete", :onclick => "return confirm('Are you sure you want to delete this image?')"

    - else
      %span.image_wrapper
        = image_tag image_path("no_image.jpg")

#food_details_div
  %h2#food_details_name= @food_item.name
  = link_to user_path(@food_item.user) do
    %p#food_details_cook= @food_item.user.full_name
  -if @current_user!=nil
    - if @current_user.following?(@food_item.user)
      = link_to 'Unfollow Cook', unfollow_user_path(@food_item.user, :food_id=>@food_item.id),:method => :get
    - else
      = link_to 'Follow Cook', follow_user_path(@food_item.user,:food_id=>@food_item.id),:method => :get
    
    
  %ul#details
    %li
      Category:
      = @food_item.category
    - if @current_user!=nil
      %li
        Distance:
        = @food_item.user.distance_from(@current_user).to_i.to_s + " miles"
    %li
      Portions:
      - if @current_user!=nil and @current_user.id == @food_item.user_id
        - @food_item.food_item_portions.each do |portion|
          %br
          Portion :
          =portion.portion
          Price :
          =portion.price
      - if @current_user!=nil and @current_user.id != @food_item.user_id
        = form_tag place_order_path do
          #myfiportions= @food_item.food_item_portions.to_json
          Portions:
          = collection_select :order, :food_item_portion, @food_item.food_item_portions, :id, :portion
          Price :
          #fooditemportionprice
          %br
          Quantity :
          = text_field :order, 'quantity', :id => 'qtyPortionsShow'
          %br
          = submit_tag 'Place Order', :id=>"placeOrderButton", :class => "action_food_item_button"
          
  %p#description= @food_item.description

- if @current_user!=nil and @current_user.id == @food_item.user_id
  #food_actions_div
    %h3 Actions
    = button_to 'Edit', edit_food_item_path(@food_item), :method => :get, :class => "action_food_item_button"
    = button_to 'Delete', food_item_path(@food_item), :method => :delete, :onclick => "return confirm('Are you sure?')", :class => "action_food_item_button"
    - if @food_item.availability
      = button_to "Make Unavailable", food_items_availability_update_path(@food_item, :food_items => {:availability => false}), :method => :put, :id => "toggle_avail", :class => "action_food_item_button"
    - else
      = button_to "Make Available", food_items_availability_update_path(@food_item, :food_items => {:availability => true}), :method => :put, :id => "toggle_avail", :class => "action_food_item_button"
    = button_to "Add Image", new_food_item_food_image_path(@food_item), :method => :get
      
= link_to "See All Reviews", food_item_food_reviews_path(@food_item), :method => :get